### ISSUE TITLE
read properties of undefined

### ISSUE THREAD

**Issue by tmkx** [ampproject/remapping#158]
`jest --coverage` output: 

FAIL  src/pages/pc/__tests__/app.node.spec.tsx
  ● Test suite failed to run

    TypeError: .../player/dist/cjs/index.js: Cannot read properties of undefined (reading 'originalPositionFor')

      at SourceMapTree.originalPositionFor (../../node_modules/.pnpm/@ampproject+remapping@2.0.1/node_modules/@ampproject/src/source-map-tree.ts:138:19)
      at trace (../../node_modules/.pnpm/@ampproject+remapping@2.0.1/node_modules/@ampproject/src/source-map-tree.ts:70:25)
      at EncodedSourceMapImpl.map (../../node_modules/.pnpm/@jridgewell+trace-mapping@0.2.2/node_modules/@jridgewell/src/encoded-map.ts:43:24)
      at TraceMap.map (../../node_modules/.pnpm/@jridgewell+trace-mapping@0.2.2/node_modules/@jridgewell/src/trace-mapping.ts:85:23)
      at SourceMapTree.traceMappings (../../node_modules/.pnpm/@ampproject+remapping@2.0.1/node_modules/@ampproject/src/source-map-tree.ts:42:26)
      at remapping (../../node_modules/.pnpm/@ampproject+remapping@2.0.1/node_modules/@ampproject/src/remapping.ts:37:30)
      at mergeSourceMap (../../node_modules/.pnpm/@babel+core@7.17.0/node_modules/@babel/core/lib/transformation/file/merge-map.js:19:30)
      at generateCode (../../node_modules/.pnpm/@babel+core@7.17.0/node_modules/@babel/core/lib/transformation/file/generate.js:72:39)
      at run (../../node_modules/.pnpm/@babel+core@7.17.0/node_modules/@babel/core/lib/transformation/index.js:55:33)
          at run.next (<anonymous>)

should ensure not nil before call the `source.originalPositionFor`?
https://github.com/ampproject/remapping/blob/e43d71e76dc54eaab3b07e6e73a217b46175e774/src/source-map-tree.ts#L137-L142

**Comment by jridgewell** [comment]
Hi @tmkx: This is actually a [bug](https://github.com/jridgewell/trace-mapping/commit/1a52383b618b0357810d8106bd575b617a1e9ba3) in `@jridgewell/trace-mapping`, which was fixed in v0.2.3. You currently have v0.2.2 installed. If you run `npm update`, does the issue still happen?

**Comment by jridgewell** [comment]
See also https://github.com/babel/babel/issues/14229
